import { state, saveState } from './state.js';
import { translateUI } from './i18n.js';

/* ─── THEME ──────────────────────────────────────────────── */
export function applyTheme(t) {
  state.currentTheme = t;
  document.body.classList.toggle('dark', t === 'dark');
  const btn = document.getElementById('theme-toggle');
  if (btn) btn.classList.toggle('on', t === 'dark');
}
export function toggleTheme() {
  applyTheme(state.currentTheme === 'light' ? 'dark' : 'light');
  saveState();
}

/* ─── LANG ───────────────────────────────────────────────── */
export function applyLang(l) {
  state.currentLang = l;
  document.querySelectorAll('.lang-btn').forEach(b => b.classList.remove('active'));
  const active = document.querySelector(`.lang-btn[data-lang="${l}"]`);
  if (active) active.classList.add('active');
  
  translateUI(l);
}
export function setLang(l) {
  applyLang(l);
  saveState();
  showToast('Language updated');
}

/* ─── TOAST ──────────────────────────────────────────────── */
export function showToast(msg, dur = 3000) {
  const w = document.getElementById('toast-wrap');
  if(!w) return;
  const t = document.createElement('div');
  t.className = 'toast';
  t.textContent = msg;
  w.appendChild(t);
  setTimeout(() => {
    t.style.opacity = '0';
    t.style.transition = 'opacity .3s';
    setTimeout(() => t.remove(), 300);
  }, dur);
}

/* ─── SIDEBAR & TABS ─────────────────────────────────────── */
export function toggleSidebar() {
  const sb = document.getElementById('sidebar');
  const bd = document.getElementById('sidebar-backdrop');
  sb.classList.toggle('open');
  bd.classList.toggle('show');
}
export function closeSidebar() {
  document.getElementById('sidebar').classList.remove('open');
  document.getElementById('sidebar-backdrop').classList.remove('show');
}

export function showTab(id, btn = null) {
  document.querySelectorAll('.panel').forEach(p => p.classList.remove('active'));
  const panel = document.getElementById('tab-' + id);
  if (panel) panel.classList.add('active');
  
  document.querySelectorAll('.nav-item').forEach(n => n.classList.remove('active'));
  if (btn) {
    btn.classList.add('active');
  } else {
    const navBtn = document.querySelector(`.nav-item[data-tab="${id}"]`);
    if (navBtn) navBtn.classList.add('active');
  }
  closeSidebar();
}

/* ─── WELCOME & EMERGENCY ────────────────────────────────── */
export function enterApp() {
  document.getElementById('welcome').classList.add('hidden');
  setTimeout(() => document.getElementById('welcome').style.display = 'none', 500);
}

export function showEmergency() { document.getElementById('emergency-overlay').classList.add('show'); }
export function hideEmergency() { document.getElementById('emergency-overlay').classList.remove('show'); }
export function callEmergency() { window.location.href = 'tel:108'; hideEmergency(); }

/* ─── PDF EXPORT ─────────────────────────────────────────── */
export function showPrint() {
  if (!state.lastResult) { showToast('No analysis to export yet.'); return; }
  const dangerLabels = { fine: 'Fine', moderate: 'Moderate', urgent: 'Urgent', emergency: 'Emergency' };
  document.getElementById('print-preview').innerHTML = `
    <strong>AdJoCare v2 – AI Medical Analysis</strong><br><br>
    <strong>Patient:</strong> ${state.lastResult.name}, ${state.lastResult.age} yrs${state.lastResult.blood ? ', Blood: ' + state.lastResult.blood : ''}<br>
    <strong>Location:</strong> ${state.lastResult.location}<br>
    ${state.lastResult.medHistory ? '<strong>History:</strong> ' + state.lastResult.medHistory + '<br>' : ''}
    <br><strong>Danger Level:</strong> ${dangerLabels[state.lastResult.dangerLevel]}<br>
    <strong>Severity:</strong> ${state.lastResult.severity}/10 · <strong>Duration:</strong> ${state.lastResult.duration || '—'}<br>
    <strong>Health Score:</strong> ${state.lastResult.healthScore}/100<br><br>
    <strong>Summary:</strong><br>${state.lastResult.summary}<br><br>
    <strong>Advice:</strong><br>${state.lastResult.advice}<br><br>
    ${state.lastResult.followUp ? '<strong>Follow-Up:</strong><br>' + state.lastResult.followUp + '<br><br>' : ''}
    <em>Generated by AdJoCare AI v2 · ${new Date().toLocaleString()}</em>
  `;
  document.getElementById('print-overlay').classList.add('show');
}
export function hidePrint() { document.getElementById('print-overlay').classList.remove('show'); }

export function downloadPDF() {
  if (!state.lastResult) return;
  hidePrint();
  try {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    const dangerLabels = { fine: 'Fine', moderate: 'Moderate', urgent: 'Urgent', emergency: 'Emergency' };
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(20);
    doc.setTextColor(29, 158, 117);
    doc.text('AdJoCare AI – Medical Report', 105, 20, { align: 'center' });
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 105, 28, { align: 'center' });
    
    doc.setDrawColor(29, 158, 117);
    doc.line(20, 32, 190, 32);

    doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.setTextColor(30, 30, 30);
    doc.text('Patient Information', 20, 42);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11);
    doc.text(`Name: ${state.lastResult.name}   Age: ${state.lastResult.age} yrs   Blood Group: ${state.lastResult.blood || '—'}`, 20, 52);
    doc.text(`Location: ${state.lastResult.location}`, 20, 60);
    if (state.lastResult.medHistory) doc.text(`Medical History: ${state.lastResult.medHistory}`, 20, 68);

    const yStart = state.lastResult.medHistory ? 76 : 68;
    doc.setDrawColor(230, 230, 230); doc.line(20, yStart, 190, yStart);
    doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.setTextColor(30, 30, 30);
    doc.text('Analysis Result', 20, yStart + 10);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(11);
    doc.text(`Danger Level: ${dangerLabels[state.lastResult.dangerLevel]}   Severity: ${state.lastResult.severity}/10`, 20, yStart + 20);
    doc.text(`Duration: ${state.lastResult.duration || 'Not specified'}   Health Score: ${state.lastResult.healthScore}/100`, 20, yStart + 28);

    doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(30, 30, 30);
    doc.text('Summary', 20, yStart + 42);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
    const sumLines = doc.splitTextToSize(state.lastResult.summary, 165);
    doc.text(sumLines, 20, yStart + 52);

    const advY = yStart + 52 + sumLines.length * 6 + 8;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(12);
    doc.text('Recommendation', 20, advY);
    doc.setFont('helvetica', 'normal'); doc.setFontSize(10);
    const advLines = doc.splitTextToSize(state.lastResult.advice, 165);
    doc.text(advLines, 20, advY + 10);

    doc.setFontSize(9); doc.setTextColor(150, 150, 150);
    doc.text('AdJoCare AI v2 – For informational purposes only. Always consult a qualified medical professional.', 105, 285, { align: 'center' });

    doc.save(`AdJoCare_Report_${state.lastResult.name.replace(/ /g, '_')}_${new Date().toLocaleDateString('en-IN').replace(/\//g, '-')}.pdf`);
    showToast('✅ PDF downloaded!');
  } catch (e) {
    console.error(e);
    window.print();
  }
}
